const Colors = {
    NodeColor: 'sienna',
    NodeBracketColor: 'darkgreen',
    NSColor: 'red',
    NameColor: 'blue',
    NodeSeparatorColor: 'black',
    NodeToggleColor: 'navy',
    AttributeColor: 'sienna',
    AttributeNSColor: 'rgb(204, 4, 204)',
    AttributeSeparatorColor: 'black',
    AttributeNameColor: 'rgb(180, 24, 3)',
    AttributeValueColor: 'rgb(5, 197, 181)',
    AttributeToggleColor: 'purple',
    AttributeAtSignColor: 'magenta',
    CDATAHeadingColor: 'rgb(104, 10, 4)',
    CDATALabelColor: 'magenta',
    CDATABodyColor: 'orange',
    CDATAToggleColor: 'brown',
    CommentHeadingColor: 'olive',
    CommentBodyColor: 'rgb(7, 201, 33)',
    CommentToggleColor: 'brown',
    PIHeadingColor: 'olive',
    PILangColor: 'darkorange',
    PIBodyColor: 'darkgreen',
    PIToggleColor: 'brown',
    TextColor: 'black',
    TextToggleColor: 'brown',
    TextBracketColor: 'navy',
    PrefixColor: 'olive',
    IsDeletedColor: 'green',
    NotDeletedColor: 'red',
    TextInputBackgroundColor: 'none',
    TextInputBorderColor: '#ccc',
    TextAreaBackgroundColor: 'none',
    TextAreaBorderColor: '#ccc',
    PrefixButtonShowColor: 'red',
    PrefixButtonHideColor: 'transparent',
    SelectedBackgroundColor: '#ccffcc',
    UnselectedBackgroundColor: 'transparent',
    OddColor: '#eee',
    EvenColor: '#fff',
}

export default Colors