const Editors = {
    NODE_EDITOR: "NODE_EDITOR",
    TEXT_EDITOR: "TEXT_EDITOR",
    CDATA_EDITOR: "CDATA_EDITOR",
    COMMENT_EDITOR: "COMMENT_EDITOR",
    PI_EDITOR: "PI_EDITOR",
    XML_DISPLAY: "XML_DISPLAY",
    CLIPBOARD: "CLIPBOARD",
}

export default Editors