const Labels = {
    NewElementMode: "Element",
    SaveElement: "Save",
    CancelElement: "Cancel",
    UnwrapElement: "Unwrap",
    NewAttribute: "New",
    SaveAttribute: "Save",
    CancelAttribute: "Cancel",
    DeleteAttribute: "Delete",
    UndeleteAttribute: "Undelete",
    NewCDATAMode: "CDATA",
    NewCommentMode: "Comment",
    NewPIMode: "PI",
    SaveText: "Save",
    CancelText: "Cancel",
    InsertNodeText: "Insert",
    CancelNodeText: "Cancel",
    InsertCDATA: "Insert CDATA",
    SaveCDATA: "Save",
    CancelCDATA: "Cancel",
    UnwrapCDATA: "Unwrap",
    InsertComment: "Insert Comment",
    SaveComment: "Save",
    CancelComment: "Cancel",
    UnwrapComment: "Unwrap",
    InsertPI: "Insert PI",
    SavePI: "Save",
    CancelPI: "Cancel",
    UnwrapPI: "Unwrap",
    CutXML: "Cut",
    CopyXML: "Copy",
    PasteXML: "Paste",
    ClearXML: "Clear",
    DeleteXML: "Delete",
    WrapXML: "Wrap",
    CancelXML: "Cancel",
    PIHeading: "PI",
    OneLine: "One Line",
    TwoLines: "Two Lines",
    ShowCloseTags: "Show Close Tags",
    HideCloseTags: "Hide Close Tags",
    CloseTags: "Close Tags",
    SelectMode: "Select Mode",
    EditMode: "Edit Mode",
    Select: "Select",
    NewDocument: "New Document",
    Normalize: "Normalize",
}

export default Labels