const Symbols = {
    NodeOpenStartCaret: "<",
    NodeOpenEndCaret: ">",
    NodeCloseStartCaret: "</",
    NodeCloseEndCaret: ">",
    NodeEmptyEndCaret: "/>",
    NodeNSSeparator: ":",
    NodeToggleOpen: " +",
    NodeToggleClose: " -",
    AttributePrefixOff: "   ",
    AttributePrefixOn: " | ",
    AttributeQuote: '"',
    AttributeEquals: "=",
    AttributeNSSeparator: ":",
    AttributeToggleOpen: "+",
    AttributeToggleClose: "-",
    AttributeOpenBracket: "[",
    AttributeAtSign: "@",
    AttributeCloseBracket: "]",
    TextToggleOpen: " -",
    TextToggleClose: " +",
    TextOpenBracket: "[",
    TextCloseBracket: "]",
    TextQuote: '"',
    TextElipsis: "...",
    CDATAOpenBracketStart: "<![",
    CDATAOpenBracketLabel: "CDATA",
    CDATAOpenBracketEnd: "[",
    CDATACloseBracket: "]]>",
    CDATAToggleOpen: " -",
    CDATAToggleClose: " +",
    CommentOpenBracket: "<!--",
    CommentCloseBracket: "-->",
    CommentToggleOpen: " -",
    CommentToggleClose: " +",
    CommentLabel: "Comment",
    PIOpenBracket: "<?",
    PICloseBracket: "?>",
    PIToggleOpen: " -",
    PIToggleClose: " +",
    DeleteIsDeleted:"+",
    DeleteNotDeleted:"𐄂",
    ButtonInsert:"+",
    ButtonEdit:"&#x1F589;",
    ButtonSave:"✓",
    ButtonCancel:"𐄂",
    PrefixOn: " |",
    PrefixOff: "  ",
    PathSeparator: "/",
    ArrowRight: "▸",
    ArrowDown: "▾",
    ArrowUp: "▴",
    ArrowLeft: "◂",
    ToggleOpen: " -",
    ToggleClose: " +"
}

export default Symbols